system:
    default:
        fielddefinition_settings_templates:
            -
                template: "BDEzPlatformQueryFieldTypeBundle::fielddefinition_settings.html.twig"
        fielddefinition_edit_templates:
            -
                template: "BDEzPlatformQueryFieldTypeBundle::field_types.html.twig"
        field_templates:
            -
                template: "BDEzPlatformQueryFieldTypeBundle::content_fields.html.twig"
