services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BD\EzPlatformQueryFieldType\Form\Type\FieldType\QueryFieldType: ~

    BD\EzPlatformQueryFieldType\Persistence\Legacy\Content\FieldValue\Converter\QueryConverter:
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: query}
