services:
    BD\EzPlatformQueryFieldType\FieldType\Query\Type:
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: query}

    BD\EzPlatformQueryFieldType\FieldType\Mapper\QueryFormMapper:
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: query }
            - { name: ez.fieldFormMapper.value, fieldType: query }
        arguments:
            $contentTypeService: '@ezpublish.api.service.content_type'
