services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BD\EzPlatformQueryFieldType\FieldType\Query\SearchField:
        tags:
            - {name: ezpublish.fieldType.indexable, alias: query}
