services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BD\PlatformQueryFieldType\GraphQL\Resolver\QueryFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "QueryFieldValue", method: "resolveQueryField" }

    BD\PlatformQueryFieldType\GraphQL\QueryFieldValueBuilder:
        tags:
            - { name: ezplatform_graphql.field_value_builder, type: 'query'}